FROM debian:jessie
MAINTAINER Yeghishe Piruzyan ypiruzyan@gmai.com

RUN apt-get update && \
    apt-get install --no-install-recommends -y curl wget jq zip unzip htop telnet build-essential python && \
